twilio/audioswitch

README.md
Add a section in the readme that links to an example app that utilizes this library.
- Add reference app section to README.md
- Validate markdown
N/A
=> Add reference app section to Readme

.circleci/config.yml, README.md, audioswitch/build.gradle, build.gradle
Publish snapshots to Jfrog OSS
- Published test snapshot to Jfrog OSS and validated I can consume the snapshot in Video Android App
=> AHOYAPPS-676 Publish snapshots to Jfrog OSS

.circleci/config.yml, build.gradle
Fix artifact upload after Android Gradle Plugin 4.0.0 Upgrade
- Tested snapshot upload from this [branch](https://app.circleci.com/pipelines/github/twilio/audioswitch/87/workflows/ab1647ec-12c7-4521-8195-4e50dafab995/jobs/355)
=> Fix artifact upload after Android Gradle Plugin 4.0.0 Upgrade

.github/ISSUE_TEMPLATE/bug_report.md
Added actual behavior section to bug report template.
=> Add actual behavior section to bug report template

CHANGELOG.md, audioswitch/build.gradle
Disabled AAR minification to fix Android Studio issues such as getting stuck in code analysis and not being able to find declarations of AudioSwitch code.
=> Disable AAR minification

README.md, audioswitch/src/test/java/com/twilio/audioswitch/BaseTest.kt, audioswitch/src/test/java/com/twilio/audioswitch/TestUtil.kt, audioswitch/src/test/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManagerTest.kt, audioswitch/src/test/java/com/twilio/audioswitch/selection/AudioDeviceSelectorJavaTest.java, audioswitch/src/test/java/com/twilio/audioswitch/selection/AudioDeviceSelectorTest.kt
Document Java Compatibility
- Add Java specific unit tests
=> AHOYAPPS-545 Document Java Compatibility

CHANGELOG.md, audioswitch/build.gradle, audioswitch/src/androidTest/java/com.twilio.audioswitch/AudioDeviceSelectorTest.kt, audioswitch/src/main/java/com/twilio/audioswitch/selection/AudioDeviceSelector.kt, audioswitch/src/test/java/com/twilio/audioswitch/selection/AudioDeviceSelectorJavaTest.java, audioswitch/src/test/java/com/twilio/audioswitch/selection/AudioDeviceSelectorTest.kt, build.gradle, gradle.properties
Add AudioSwitch version constant
- Unit and integration test
=> AHOYAPPS-819 Add AudioSwitch version constant

audioswitch/src/androidTest/AndroidManifest.xml, audioswitch/src/androidTest/java/com.twilio.audioswitch/ConnectedBluetoothHeadsetTest.kt, audioswitch/src/androidTest/java/com.twilio.audioswitch/TestUtil.kt
Add connected bluetooth device instrumentation test. This suite of tests helps us add better test coverage with respect to bluetooth devices.
- Local development
=> Add connected bluetooth device instrumentation test

CHANGELOG.md
Fake PR to give @tejas-n credit for his work in #39.
=> Attribute Tejas

audioswitch/src/androidTest/java/com.twilio.audioswitch/TestUtil.kt, audioswitch/src/main/java/com/twilio/audioswitch/AudioDeviceManager.kt, audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt, audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchJavaTest.java, audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchTest.kt, audioswitch/src/test/java/com/twilio/audioswitch/BaseTest.kt
This PR simplifies the constructors to one point of initialization execution. Additionally, this PR includes a reorganization of the AudioSwitch files to follow the [Kotlin Coding Conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#class-layout).
- CI
=> Reorganize AudioSwitch Constructors and Properties

CONTRIBUTORS.md
Add to CONTRIBUTORS.md according to the discussion in https://github.com/twilio/audioswitch/issues/38#issuecomment-674113159
=> Add to CONTRIBUTORS.md

CHANGELOG.md, gradle.properties
- Promotes 0.4.0 to the first stable release of this library.
=> Release 1.0.0

CHANGELOG.md, build.gradle
=> Upgrade Kotlin to 1.4.0

.github/ISSUE_TEMPLATE/bug_report.md, README.md
Updated README and new issue template based on feedback from #79 thanks to @rocboronat.
=> Readme and issue template update

CHANGELOG.md, audioswitch/build.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties
Upgraded gradle version used by audioswitch.
- upgraded androidx dependencieny
- upgraded gradle version
- everything ran and compiled
none
=> Upgraded gradle version to 7.x

CHANGELOG.md
Updated changelog
- Updated changelog to reflect community authored fix.
- Ran all test cases
- Tested user changes in Ahoy app
None
=> VIDEO-10369 Updated changelog to reflect user submitted fixes in preparation for release

audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManager.kt
=> Check app's targetSdkVersion instead of device version for Bluetooth permission checking

CHANGELOG.md
Update changelog to reflect recent improvments.
- Changelog updated
-N/A
-N/A
=> Updated CHANGELOG for release

CHANGELOG.md, build.gradle
Updated to be able to update version on release
- update build.gradle
- Updated build.gradle to use github token
=> Tast/video 12647/release audio switch

CHANGELOG.md
Updated changelog to reflect build tools upgrade
- Changelog updated
- N/A
=> Updated Changelog to reflect Android build tools  upgrade to 8.0.2

.circleci/config.yml, CHANGELOG.md, build.gradle, gradle/wrapper/gradle-wrapper.properties
Upgraded AGP
- Upgraded AGP to 8.3.1
- Ran CI tests
None
=> VBLOCKS-2909: upgraded audioswitch

CHANGELOG.md, gradle.properties
Prep for release. Update CHANGELOG.md and version
- Update CHANGELOG.md
- Bump version 1.2.0
- CI run
=> Update CHANGELOG.md and version

CHANGELOG.md
Updated changelog for 1.2.1 release
- Updated changelog
- N/A
none
=> updated Changelog for 1.2.1 release

.circleci/config.yml, build.gradle
Update maven release process
- Updated maven release processes
- Added new username/token
- Added new target url
- Removed snapshot functionality as its not available via the current structure.   
- made release
None
=> [VBLOCKS-4948] Updated to reflect changes to maven central and OSSRH removal

CHANGELOG.md, build.gradle, gradle.properties
Fixed a minor release issue
- Username included in github remote url
- ran from CI
Please note that the changelog has been modified to use the version 1.2.5 for the in-progress version as I plan on making a release to test that the issue is fixed.
=> Fix release issue

audioswitch/src/main/java/com/twilio/audioswitch/AudioDeviceManager.kt, audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt, audioswitch/src/main/java/com/twilio/audioswitch/android/BluetoothIntentProcessorImpl.kt, audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManager.kt
Updated deprecated methods to modern alternatives with fallbacks for older API levels.
Resolved warnings.
Tested locally with Voice Quickstart app
=> QSDK-11074: Review deprecated dependencies/methods
