.circleci/config.yml
CHANGELOG.md
audioswitch/build.gradle

Add sources to release artifacts
- Published a test [artifact](https://bintray.com/twilio/internal-releases/audioswitch/0.1.2-329289c) and validated that when consumed in the Video app that the sources are available.

AHOYAPPS-611 Add sources to release artifacts

---

CHANGELOG.md
audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetReceiver.kt
audioswitch/src/test/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetReceiverTest.kt

Added additional device classes to support more bluetooth headset devices.
- Added `AUDIO_VIDEO_HEADPHONES` and `UNCATEGORIZED` as additional supported device classes in `BluetoothHeadsetReceiver`.
- Passed CI
I tried utilizing the BluetoothHeadset proxy object retrieved from the BluetoothAdapter class within the BluetoothDeviceReceiver class as an alternative to checking device classes , but had no luck. I tried referencing the getDevicesMatchingConnectionStates and getConnectedDevices methods from the BluetoothHeadset proxy to check if the device received from the ACTION_ACL_CONNECTED  receiver event was indeed connected, but those methods just returned an empty list. Perhaps our BluetoothDeviceReceiver is receiving events before they are being connected with the BluetoothHeadset proxy. …

AHOYAPPS-653: Add additional device classes to support more bluetooth headset devices

---

CHANGELOG.md
audioswitch/src/main/java/com/twilio/audioswitch/android/BluetoothDeviceWrapperImpl.kt
audioswitch/src/test/java/com/twilio/audioswitch/selection/AudioDeviceSelectorTest.kt

Fixed crash by adding default bluetooth device name if null is returned from the Android BluetoothDevice class. Resolves issue reported in #22 . 
- Passed CI pipeline

Add default bluetooth device name

---

audioswitch/proguard-rules.pro

Add configuration to proguard-rules.pro to ignore all audio switch files for obfuscation.
- Manually pushed an artifact to OSS JFrog and tested artifact consumption in the Twilio Video App.

Don't obfuscate the audio switch library

---

CHANGELOG.md
audioswitch/src/main/java/com/twilio/audioswitch/selection/AudioDeviceManager.kt
audioswitch/src/test/java/com/twilio/audioswitch/bluetooth/BaseTest.kt
audioswitch/src/test/java/com/twilio/audioswitch/selection/AudioDeviceSelectorTest.kt

Fixed a bug where the audio focus wasn't being returned to the previous audio focus owner on pre Oreo devices.
Fixes issue #38.
Based off of original pull request by @tejas-n #39.
- In `AudioDeviceManager`, Store a reference to onAudioFocusChangeListener that was used to request audio focus and use it with abandonAudioFocus(..) so that the framework can give back the audio focus to the previous owner.
- Manually tested on a Pixel 3 and Hesh 2 Wireless and LE-Bose NC 700 HP bluetooth headsets.
- Passed CI Pipeline
Thank you @tejas-n for the contribution! Excellent work 🎉

Audio focus fix for pre Oreo devices

---

CHANGELOG.md
audioswitch/src/androidTest/java/com.twilio.audioswitch/AudioFocusUtil.kt
audioswitch/src/androidTest/java/com.twilio.audioswitch/AudioSwitchIntegrationTest.kt
audioswitch/src/androidTest/java/com.twilio.audioswitch/TestUtil.kt
audioswitch/src/androidTest/java/com/twilio/audioswitch/manual/ConnectedBluetoothHeadsetTest.kt
audioswitch/src/main/java/com/twilio/audioswitch/AudioDeviceManager.kt
audioswitch/src/main/java/com/twilio/audioswitch/AudioFocusRequestWrapper.kt
audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt
audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchJavaTest.java
audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchTest.kt
audioswitch/src/test/java/com/twilio/audioswitch/BaseTest.kt

Resolves issue #53  .
Based on original PR #54 opened by @agnusin.
Added another constructor parameter that allows developers to subscribe to system audio focus changes while the library is activated.
- Passed CI.
N/A

AHOYAPPS-824: Add public audio focus change listener

---

.circleci/config.yml

The `UseContainerSupport` is now used in place of the `UseCGroupMemoryLimitForHeap` JVM argument since it is no longer supported in the latest Java 11 docker image.

Remove broken JVM arg from upgrade to java 11

---

CHANGELOG.md
audioswitch/src/main/java/com/twilio/audioswitch/android/SystemClockWrapper.kt

Added the internal access modifier to the `SystemClockWrapper` class since it is not meant to be exposed publicly. Thanks to @4brunu for finding this out as part of issue #67!
- Passed CI.

Add internal access modifier to the SystemClockWrapper class

---

CHANGELOG.md
audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt

The `AudioSwitch` public constructor now retrieves the application context from the context passed in from the client.
- Passed CI.

AHOYAPPS-840: Retrieve application context

---

audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt

Fixes a typo in the docs for `selectDevice`
No new changes

Fix typo in documentation for selectDevice

---

CHANGELOG.md
audioswitch/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

Upgraded AGP to 4.1.1 and upgraded the test dependencies. Also added `VERSION_NAME` as a build config field since AGP 4.1.1 removed it by default for Android libraries.
- Passed CI

Upgrade AGP to 4.1.1

---

.circleci/config.yml
CHANGELOG.md
CONTRIBUTORS.md
audioswitch/build.gradle
build.gradle

This PR adds Maven Central publishing to the Audioswitch project. Previously Audioswitch was published to JCenter, but due to their pending shutdown of the service, we needed to migrate to a new artifact provider.
This PR uses the [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) to manage multitenancy and closing and releasing Next staging repositories.
A few new environment variables were added to the CircleCI settings to assist with this:
* `OSSRH_USERNAME`: The username for the MavenCentral repository. We are actually using a user token here for our `twilio-sdk-build` user.
* `OSSRH_PASSWORD`: The password for the MavenCentral repository. Again, in this case this is the user token password.
* `SONATYPE_STAGING_PROFILE_ID`: The MavenCentral staging …

VIDEO-4165: Deploy to MavenCentral

---

ui-test-args.yaml

Replaces the SM-A520F device in firebase test lab as it is no longer supported.
- Passes CI

Replace no longer supported SM-A520F FTL device

---

CHANGELOG.md
README.md

Remove references to Bintray and point to MavenCentral
- Updated `README.md` and `CHANGELOG.md` to refer to Maven Central instead of Bintray
- 👀 

Update docs for MavenCentral consumption [skip ci]

---

CHANGELOG.md
README.md
build.gradle

Move mavenCentral() above jcenter() in the project level build.gradle repositories block. Also fixed some formatting.

VIDEO-4537: Move mavenCentral() above jcenter()

---

.circleci/config.yml
CHANGELOG.md
CONTRIBUTORS.md
README.md
audioswitch/build.gradle
build.gradle
gradle.properties

JFrog no longer supports publication of snapshots. This PR provides the changes needed to publish audioswitch snapshots to MavenCentral instead. I also took the opportunity to refactor the Circle CI configuration a bit.
Gradle changes:
- remove references to artifactory
- publish snapshots to maven central snapshots repository
- remove obsolete `jcenter` from repositories
Circle CI changes:
- refactor Circle CI config file to use commands and executors
- add parameter for pre-release publishing to maven central
- add parameter for disabling default CI workflow 
- add parameter and workflow for publishing a snapshot from any branch
- add comments and do other minor refactoring in CI config
Other changes:
- restore patch version number to 3, since that is the next version to be published
- …

VIDEO-7662: Publish snapshots to MavenCentral

---

README.md

Adding the Maven Central snapshots repository with `snapshotsOnly` restriction causes releases not to be located correctly. Removing this restriction fixes that problem. 
- remove snapshotsOnly from maven repository spec
- tried it with a release and a snapshot and validated that both work

Update README: remove snapshotsOnly from snapshots instructions

---

CHANGELOG.md
build.gradle
gradle.properties

Upgraded Dokka dependency so that the docs can be generated again.
Updated dokka version to 1.4.32
Was able to build documentation.
none
- [*] The source has been evaluated for semantic versioning changes and are reflected in `gradle.properties`
- [*] The `CHANGELOG.md` reflects any **feature**, **bug fixes**, or **known issues** made in the source code

VIDEO-7698 dokka upgraded so docs can be generated

---

CHANGELOG.md
audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt
audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManager.kt
audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchTest.kt
audioswitch/src/test/java/com/twilio/audioswitch/BaseTest.kt
audioswitch/src/test/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManagerTest.kt

Fixed two issues, one is caused when Bluetooth permissions are granted after audioswitch has been started and audio switch is subsequently stopped. The other issue has existed for some time and is the result of devices sending multiple disconnect events.
- Fixed issue where InvalidStateException on audioswitch.stop(..) was being thrown when the bluetooth subsystem was not registered due to lack of permissions.
- Fixed issue where spurious audioDeviceChanged events were being sent as a reaction to spurious events from system.
- Added test case to test spurious audioDeviceChanged events
- Tested both use-cases outlined by customer
- Added unit test case for spurious events
None
- [*] The source has been evaluated for semantic versioning changes and are reflected in `gradle.properties`
- [*] …

VIDEO-7850 Spurious events and Invalid State Exception issue

---

.circleci/config.yml
CHANGELOG.md

Circle CI has deprecated the circleci/* docker images in favor of the new cimg/* images, this PR replaces the obsolete image with an appropriate new version.
Also, dates have been added for the changelog release entries.

Replace outdated circleci docker image and add dates to changelog

---

audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothScoJob.kt

As seen in https://github.com/twilio/audioswitch/issues/119
When switching away from a Bluetooth headset to the speaker (for example), then switching back to the Bluetooth headset, a few seconds later the audio will be switched back to the "earpiece".
After debugging this, I found that this happens because there are multiple `EnableBluetoothScoJob` runnables running, with one of them timing out, therefore causing the `AudioActivationError` state to be set and causing the behaviour of the connection having errored, although this isn't the case and audio is still heard through the BT headset.
This fixes the problem by ensuring that when we start a new `EnableBluetoothScoJob`, we cancel the existing runnable first (if it exists).
- Added call to `Handler::removeCallbacks` within the …

Fix issue #119 by ensuring the existing runnable is cancelled

---

audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManager.kt
ui-test-args.yaml

In a scenario where targetSdkVersion > 30 and device sdk version <= 30 bluetooth permission check would look into incorrect permission for the device and thus return false which in return would fail to initialise bluetooth capabilities.
[Description of the Pull Request]
- Adding or for devices under 30 api level in bluetooth permission check
- Update FTL device list
- [CI link](https://app.circleci.com/pipelines/github/twilio/audioswitch/528/workflows/55728c21-737d-43c4-9191-07015aaacedd)
- Manually check that when targetSdkVersion <= 30 and device SDK > 30 is selecting bluetooth headset and theres audio flow
- Manually check that when targetSdkVersion > 30 and device SDK <= 30 is selecting bluetooth headset and theres audio flow
[Any additional comments, notes, or information relevant to …

Bug/video 12475/bluetooth integration tests

---

audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt

`enumerateDevices()` method call from wired and bluetooth connection receivers could overlap with `enumerateDevices()` call when AudioSwitch is started. This lead to two potential issues, especially when AudioSwitch was stoped and then restarted:
- ConcurrentModificationException for the device list
- Duplication of entries in the device list
- Moving initial `enumerateDevices()` up in order before starting connection listeners
- [Bulleted summary of validation steps]
- [eg. Add new unit tests to validate changes]
- [eg. Verified all CI checks pass on the feature branch]
Related reported issues:
https://github.com/twilio/audioswitch/issues/114
https://github.com/twilio/audioswitch/issues/120

Enumerate devices first before starting connection listeners

---

CHANGELOG.md
audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt

Move AudioSwitch state change at the beginning of every flow execution, to eliminate two potential race conditions:
- Incorrect state and exception thrown when selected device is activated shortly after starting the AudioSwitch
- Bluetooth device is reactivated after stopping AudioSwitch due to incorrect state which caused permanent audio focus (only fixed by reconnecting the Bluetooth device). This also made device to not appear on the list since it was always in active audio connected state.
- Move state change before any other execution
- [Bulleted summary of validation steps]
- [eg. Add new unit tests to validate changes]
- [eg. Verified all CI checks pass on the feature branch]

Race conditions in changing states

---

CHANGELOG.md
README.md
audioswitch/src/androidTest/java/com.twilio.audioswitch/AudioSwitchIntegrationTest.kt
audioswitch/src/androidTest/java/com.twilio.audioswitch/AutomaticDeviceSelectionTest.kt
audioswitch/src/androidTest/java/com.twilio.audioswitch/TestUtil.kt
audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt
audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetConnectionListener.kt
audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManager.kt
audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchJavaTest.java
audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchTest.kt
audioswitch/src/test/java/com/twilio/audioswitch/BaseTest.kt
audioswitch/src/test/java/com/twilio/audioswitch/TestUtil.kt
audioswitch/src/test/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManagerTest.kt

Bluetooth listener can now be added to AudioSwitch to monitor bluetooth device connections.
- Make BluetoothHeadsetConnectionListener public
- BluetoothHeadsetConnectionListener onBluetoothHeadsetStateChanged now also returns state
- Update README and CHANGELOG
- Update tests and add test case for BluetoothHeadsetConnectionListener
- [Bulleted summary of validation steps]
- [eg. Add new unit tests to validate changes]
- [eg. Verified all CI checks pass on the feature branch]

VBLOCKS-2801 bluetooth listener

---

CHANGELOG.md
README.md
audioswitch/src/androidTest/AndroidManifest.xml
audioswitch/src/androidTest/java/com.twilio.audioswitch/TestUtil.kt
audioswitch/src/main/AndroidManifest.xml
audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt
audioswitch/src/main/java/com/twilio/audioswitch/android/BluetoothDeviceWrapperImpl.kt
audioswitch/src/main/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManager.kt
audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchJavaTest.java
audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchTest.kt
audioswitch/src/test/java/com/twilio/audioswitch/BaseTest.kt
audioswitch/src/test/java/com/twilio/audioswitch/bluetooth/BluetoothHeadsetManagerTest.kt

BLUTOOTH_CONNECT or BLUETOOTH permission is now optional. When bluetooth permissions are not granted by the app using AudioSwitch the bluetooth devices will not appear or be selectable.
- Remove BLUTOOTH_CONNECT and BLUETOOTH permissions from Manifest
- Move bluetooth permission check to AudioSwitch class
- Remove permission checks from BluetoothHeadsetManager
- Update unit and integration tests
- Tests pass
- Run manual validation with voice quickstart

VBLOCKS-2802 Bluetooth permissions

---

CHANGELOG.md
audioswitch/src/androidTest/java/com.twilio.audioswitch/TestUtil.kt
audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt
audioswitch/src/test/java/com/twilio/audioswitch/AudioSwitchJavaTest.java
audioswitch/src/test/java/com/twilio/audioswitch/BaseTest.kt

BluetoothHeadsetManager should check permission when invoked
[Description of the Pull Request]
- Check if BluetoothHeadsetManager is not initialised and bluetooth permissions are granted, in that case create a new instance
- Remove deprecated BluetoothAdapter.getDefaultAdapter() in favour of BluetoothManager.adapter
- [Bulleted summary of validation steps]
- [eg. Add new unit tests to validate changes]
- [eg. Verified all CI checks pass on the feature branch]

VBLOCKS-3880 BluetoothHeadsetManager should check permission when invoked

---

audioswitch/src/androidTest/java/com/twilio/audioswitch/manual/ConnectedBluetoothHeadsetTest.kt
audioswitch/src/main/java/com/twilio/audioswitch/AudioSwitch.kt
audioswitch/src/test/java/com/twilio/audioswitch/BaseTest.kt
ui-test-args.yaml

- Fixed issue where the audio device list is not updated after a permissions request
- Fixed issue where BluetoothHeadsetManager were being created more than necessary
- Upon an activity resume, the device list is updated
- 'instance' method replaces with method that updates bluetoothHeadsetManager member
- Updated FTL device list
- Tested with RN client
- Ran device tests
None

[VBLOCKS-4911] Fix issue when output list is not updated after permissions approval
